---
title: "<span style='color: #982568; font-size:42px'>OpenAirQ Toolkit</style>"
author: "Developed for the Partnership for Healthy Cities with support from Bloomberg Philanthropies. Last Updated : `r Sys.Date()` on `r R.Version()$version.string`"
output: bookdown::gitbook
documentclass: book
---

# Introduction {-}
This toolkit provides and **introduction to spatial data processing and analysis in R** for air quality analysis applications, allowing researchers, policymakers, analysts, and practicioners to gain data-driven air quality insights in their local community. After completing out tutorials, you will have the tools to replicate our analysis or perform similar analyses on a new geography of your choosing.

This toolkit is divided into two sections. A first section detailing the air quality analyses done for the Chicagoland area, and a secondary appendix with tutorials on how to collect open-source air quality data from reputable government sources like the EPA and NASA. All data used in the tutorial is hosted on a GitHub repo named [OpenAirQ-toolkit](https://github.com/GeoDaCenter/OpenAirQ-toolkit/tree/master/data).

## Software Basics {-}
Tutorials assume that R and RStudio is already downloaded on your device. Luckily, this toolkit is compatible with Windows, macOS, and Linux systems. Basic familiarity in R is required for these toolkits. You should know how to change the working directory, install new packages, library packages, and comfortably navigate between folders on your computer. Additionally, an internet connection will be required for some tutorials.

If you are new to R, we recommend the following <a href="https://learn.datacamp.com/courses/free-introduction-to-r">intro-level tutorials</a> provided through <a href="https://rspatial.org/intr/1-introduction.html">installation guides</a>. You can also refer to this <a href="https://datacarpentry.org/r-socialsci/">R for Social Scientists</a> tutorial developed by Data Carpentry for a refresher.

Before we begin, install the following packages for data wrangling and spatial data analysis.

* `sf`, for vector spatial data manipulation
* `sp`, for vector & raster data manipulation
* `raster`, for raster data manipulation
* `tmap`, for cartography and mapmaking in R
* `dplyr`, for data frame manipulation

## Author Team {-}
This toolkit was created by Marynia Kolak, Isaac Kamber, Lorenz Menendez, Haowen Shang, Yuming Liu, Jizhou Wang, and Andrew Morse at the [Center for Spatial Data Science](https://spatial.uchicago.edu/) at the University of Chicago.

## Acknowledgements {-}
This toolkit was developed with support from the [Partnership for Healthy Cities](https://partnershipforhealthycities.bloomberg.org/), a global network funded by Bloomberg Philanthropies in partnership with the World Health Organization and the global health organization Vital Strategies.

***

